version: '3.8'
services:
  backend:
    build: ./backend
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb+srv://apurbapatra12:apurbaP@Cluster0.dovgxio.mongodb.net/
      - JWT_SECRET=abcedddsodadsada556547
      - JWT_EXPIRES_IN=7d
      - FRONTEND_URL=http://localhost:3000

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend